services:

  qgd_postgres_db:
    image: postgis/postgis:latest
    container_name: qgd_db
    restart: always
    ports:
      - "3022:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data


  qgd_backend:
    build: ./backend
    depends_on:
      - qgd_postgres_db
    container_name: qgd_backend
    restart: always
    volumes:
      - ./backend:/code
    ports:
      - 8021:8000
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M

  qgd_frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - qgd_backend
    container_name: qgd_frontend
    restart: always
    ports:
      - 3021:3000
    env_file:
      - ./frontend/.env
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M

volumes:
  postgres-data: