"""add is_published to dashboards

Revision ID: ef96b454f570
Revises: 32ce6e0f6a5a
Create Date: 2026-03-27 02:34:43.415841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef96b454f570'
down_revision: Union[str, Sequence[str], None] = '32ce6e0f6a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'is_published')
    # ### end Alembic commands ###
